<footer class="bg-secondary text-center text-lg-start mt-5">
    <div class="container p-4">
        <div class="row">
            <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                <h5 class="text-uppercase text-white ">Acerca de nosotros</h5>

                <p class="text-white">
                    Nuestro objetivo es ofrecer una selección única de mates, cuidadosamente seleccionados para mantener viva la cultura del mate. Nos dedicamos a proporcionar productos de alta calidad para que cada mate compartido sea una experiencia especial. ¡Explorá nuestro catálogo y encontrá el mate perfecto para vos!
                </p>

            </div>

            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

                <h5 class="text-uppercase text-white">Enlaces útiles</h5>
                <ul class="list-unstyled mb-0">
                    <li><a href="#" class="text-white">Política de privacidad</a></li>
                    <li><a href="#" class="text-white">Términos de uso</a></li>
                    <li><a href="#" class="text-white">FAQ</a></li>
                </ul>
            </div>

            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase text-white">Síguenos</h5>
                <ul class="list-unstyled mb-0">
                    <li><a href="#" class="text-white">Facebook</a></li>
                    <li><a href="#" class="text-white">Twitter</a></li>
                    <li><a href="#" class="text-white">Instagram</a></li>
                </ul>
            </div>

        </div>
    </div>


    <div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2024 ChampiMates - Todos los derechos reservados.
    </div>

</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>