<div class="container mt-5">

    <form method="POST" action="<?= BASE_URL ?>agregar">

        <div class="form-group">
            <label for="nombre_mate">Nombre del Mate</label>
            <input type="text" class="form-control" id="nombre_mate" name="nombre_mate" required>
        </div>


        <div class="form-group">
            <label for="forma_mate">Forma del Mate</label>
            <input type="text" class="form-control" id="forma_mate" name="forma_mate" required>
        </div>


        <div class="form-group">
            <label for="recubrimiento_mate">Recubrimiento del Mate</label>
            <input type="text" class="form-control" id="recubrimiento_mate" name="recubrimiento_mate" required>
        </div>


        <div class="form-group">
            <label for="imagen">URL de la Imagen</label>
            <input type="url" class="form-control" id="imagen" name="imagen" required>
        </div>


        <div class="form-group">
            <label for="color_mate">Color del Mate</label>
            <input type="text" class="form-control" id="color_mate" name="color_mate" required>
        </div>


        <label for="id_categoria_fk">Categoría:</label>


        <select name="id_categoria_fk" id="id_categoria_fk" required>

            <?php
            foreach ($categorias as $categoria): ?>
                <option value="<?= $categoria->id_categoria; ?>"><?= $categoria->material_fabricacion; ?></option>
            <?php endforeach; ?>

        </select>

        <button type="submit" class="btn btn-primary mt-3">Agregar Mate</button>
    </form>
</div>