<div class="container mt-5">
    <h1 class="mb-4">Productos</h1>


    <?php if (isset($_SESSION['USER_NAME'])) { ?>
        <a href="agregar" class="btn btn-success mb-4">Agregar nuevo mate</a>
    <?php } ?>


    <div class="row">
        <?php foreach ($products as $product): ?>
            <div class="col-md-4">
                <div class="card mb-4">

                    <div class="card-body">

                        <h3 class="card-title"><?= $product->nombre_mate ?></h3>


                        <img class="img-fluid" src="<?= $product->imagen ?>">


                        <h4 class="card-title">Tipo del mate: <?= $product->forma_mate ?></h4>

                        <h4 class="card-title">Material de fabricacion: <?= $product->material_fabricacion ?></h4>




                        <a href="mostrar/<?= $product->id_mate; ?>" class="btn btn-warning">Ver detalles</a>


                        <?php if (isset($_SESSION['USER_NAME'])) { ?>
                            <a href="editar/<?= $product->id_mate; ?>" class="btn btn-info">Editar</a>

                            <a href="eliminar/<?= $product->id_mate; ?>" class="btn btn-danger">Eliminar</a>
                        <?php } ?>

                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>