<div class="container mt-5">
    <h1 class="mb-4">Productos</h1>
    <a href="agregar" class="btn btn-success mb-4">Agregar nuevo mate</a>
    <div class="row">
        <?php foreach ($products as $product): ?>
            <div class="col-md-4">
                <div class="card mb-4">

                    <div class="card-body">
                        <h3 class="card-title"><?= $product->nombre_mate ?></h3>

                        <img class="img-fluid" src="<?= $product->imagen ?>">

                        <h3 class="card-title">Tipo del mate: <?= $product->forma_mate ?></h3>

                        <h3 class="card-title">Material de fabricacion: <?= $product->material_fabricacion ?></h3>



                        <a href="mostrar/<?= $product->id_mate; ?>" class="btn btn-info">Ver detalles</a>
                        <a href="editar/<?= $product->id_mate; ?>" class="btn btn-info">Editar</a>
                        <a href="eliminar/<?= $product->id_mate; ?>" class="btn btn-info">Eliminar</a>


                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>